### ISSUE TITLE
why not deploy on Fargate instead of ec2?

### ISSUE THREAD

**Issue by d3287t328** [zcemycl/aws-chromadb-terraform#1]
Ssh is depreciated and goes against devops and gitops principles. Please make a version that builds the apps with Docker and deploys on Fargate.

**Comment by zcemycl** [comment]
@d3287t328 I just have that in architecture 4 -- apigw-nlb-ecs. But still figuring out efs attachment to fargate.

**Comment by zcemycl** [comment]
@d3287t328 Done :)
