### ISSUE TITLE
Error: Warning: Argument is depreciated

### ISSUE THREAD

**Issue by Shubham-Khichi** [zcemycl/aws-chromadb-terraform#2]
Whenever I type` terraform plan` or `terraform apply -auto-approve` I get this error message: 

❯ terraform apply -auto-approve
╷
│ Warning: Argument is deprecated
│
│   with module.public_subnet_network.aws_eip.nat_gateway,
│   on ../../modules/subnets/main.tf line 36, in resource "aws_eip" "nat_gateway":
│   36:   vpc   = true
│
│ use domain attribute instead
│
│ (and 2 more similar warnings elsewhere)
╵
╷
│ Error: Unsupported attribute
│
│   on instances.tf line 60, in resource "aws_instance" "chroma_instance":
│   60:     module.security_groups.chroma_instance_sg_id
│     ├────────────────
│     │ module.security_groups is a object
│
│ This object does not have an attribute named "chroma_instance_sg_id".
╵
╷
│ Error: Unsupported attribute
│
│   on instances.tf line 89, in resource "aws_instance" "backdoor_instance":
│   89:     module.security_groups.backdoor_instance_sg_id
│     ├────────────────
│     │ module.security_groups is a object
│
│ This object does not have an attribute named "backdoor_instance_sg_id".

**Comment by zcemycl** [comment]
@Ghostyboy0719 which architecture are you running? The potential cause is the modules outputs don't contain the attribute referred from another resources.

**Comment by Shubham-Khichi** [comment]
#3

**Comment by zcemycl** [comment]
@Ghostyboy0719 okay... I will debug it later.

**Comment by zcemycl** [comment]
@Ghostyboy0719 The bug has been resolved.
